name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
      
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/elmo
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: ${{ env.GOPATH }}/src/elmo

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: get dependencies
      run: go get -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
